### ISSUE TITLE
Gebäudefotos und Platzhalterbilder

### ISSUE THREAD

**Issue by timoloewe** [lmu-navigator/android#2]
Platzhalter z.B. im Style von Google Contacts App.

**Comment by timoloewe** [comment]
Was hier noch fehlt:
- Es fehlen uns noch Fotos von einigen Gebäuden (low prio)
- Es fehlt uns ein Platzhalterbild, das wir anzeigen, falls wir kein Foto haben (high prio)
- Das Foto, das wir derzeit für das Hauptgebäude verwenden, ist nicht von uns und die Rechte sind mir unklar. Wir müssen recherchieren, ob wir es benutzen dürfen oder es austauschen (high prio)

**Comment by timoloewe** [comment]
Das Foto vom Hauptgebäude kommt von der LMU Facebook Seite. @lukasziegler Weißt du, ob wir das verwenden dürfen oder kannst du deswegen nachfragen?

**Comment by timoloewe** [comment]
Hauptgebäudefoto hab ich ausgetauscht. Fehlt noch ein Platzhalterbild. Werde mich am Wochenende mal dransetzen eins per Code zu erstellen...

**Comment by lukasziegler** [comment]
Soll ich versuchen eins in Graustufen zu entwerfen? Falls du schon
bestimmte Vorstellungen bzw Anforderungen an das Platzhalter Bild hast,
lass es mich wissen, dann versuche ich heute und morgen auch mal was ich
zustande bekomme.
Timo Loewe notifications@github.com schrieb am Sa., 17. Okt. 2015 um
00:17:

**Comment by timoloewe** [comment]
Danke, aber ich habe schon mehr oder weniger eine Lösung dafür!

**Comment by timoloewe** [comment]
Placeholders sind fertig :white_check_mark: 6dcf89727ecf13fe3738302eb933f95e2d24bb51
