### ISSUE TITLE
Datenbank per App-Update aktualisieren

### ISSUE THREAD

**Issue by timoloewe** [lmu-navigator/android#7]
Mit Server-Download ist es unpraktisch, fehleranfällig und führt zu Inkonsistenzen bei den Sample-Bilder. Außerdem kann die App beim ersten Start ohne Internetverbindung nicht benutzt werden.

Wir sollten stattdessen die Datenbank nur bei App-Updates aktualisieren und müssen dafür auf dem Server eventuell mehrere Versionen der Kacheln bereitstellen (v1, v2, v3, usw).

**Comment by lukasziegler** [comment]
@dmo60, brauchst du hierzu Hilfe von mir bzw. Änderungen am Server?

**Comment by timoloewe** [comment]
@lukasziegler Danke Lukas, die Arbeit liegt hier eigentlich nur auf Seiten der App, am Server gibt es quasi nichts zu tun, außer, dass wir mehrere Ordner mit Kacheln anlegen müssen.

**Comment by timoloewe** [comment]
:white_check_mark: 6b04ffd877ac17bbc5ad474073fffc8531cc3e7a
